### ISSUE TITLE
combo box for flags 

### ISSUE THREAD

**Issue by WoodgamerHD** [Exlodium/CS2-External-Base#3]
and this on top of "Gui::Render( )"
const char* FlagsNames[] = {
    "Money flag",
    "Armor flag",
    "Kit flag",
    "Defusing flag",
    "Zoom flag"
};

put this in "Gui::Render( )"
  static bool selected[5] = { false, false, false, false, false };
  if (ImGui::BeginCombo("Flags", "Select Flags"))
  {
      for (int i = 0; i < 5; i++)
      {
          ImGui::Checkbox(FlagsNames[i], &selected[i]);
      }
      ImGui::EndCombo();
  }

  // Handle changes to the flags here
  for (int i = 0; i < 5; i++) {
      Variables::Visuals::m_arrFlags[i] = selected[i];
  }

https://i.imgur.com/Kx74YCf.png

**Comment by Exlodium** [comment]
Added multicombo boxes to the base
