### ISSUE TITLE
Weapon Esp

### ISSUE THREAD

**Issue by WoodgamerHD** [Exlodium/CS2-External-Base#4]
pic of how it looks
https://i.imgur.com/JrjBNv1.png

if (Variables::Visuals::m_bWeapon)
	Drawweapon(
		pPawn,
		ImVec2(vecScreenHead.x, vecScreenFeet.y + this->m_arrPadding.at(DIR_BOTTOM)),
		Color(255, 255, 255, 255),
		Variables::Visuals::m_colOutline
	);

offsets 

 inline constexpr std::ptrdiff_t m_pClippingWeapon = 0x1290;

 inline constexpr std::ptrdiff_t m_szName = 0xC18;

add this in to "CCSPlayerPawn"
const std::string GetWeaponName()
  {
    
      const auto clippingWeapon = Globals::m_Memory.Read<std::uint64_t>((reinterpret_cast<uintptr_t>(this) + Offsets::m_pClippingWeapon));
      const auto weaponData = Globals::m_Memory.Read<std::uint64_t>(clippingWeapon + 0x360);
      const auto weaponNameAddress = Globals::m_Memory.Read<std::uint64_t>(weaponData + Offsets::m_szName);
      std::string weaponName = "Invalid Weapon Name";

      if (!weaponNameAddress) {
          weaponName = "Invalid Weapon Name";
      }
      else {
          char buf[32];
          Globals::m_Memory.ReadRaw(weaponNameAddress, buf, sizeof(buf));
          weaponName = std::string(buf);
      }

      return weaponName;
  }

void CPlayerESP::Drawweapon(CCSPlayerPawn* pEntity, ImVec2 vecPosition, Color colColor, Color colOutline)
{
	const std::string weaponName = pEntity->GetWeaponName();
	const ImVec2 vecNameSize = Fonts::ESP->CalcTextSizeA(10.0f, FLT_MAX, 0.0f, weaponName.c_str());
	Draw::AddText(Fonts::ESP, 10.0f, ImVec2(vecPosition.x - vecNameSize.x * 0.5f, vecPosition.y), weaponName.c_str(), colColor, DRAW_TEXT_OUTLINE, colOutline);
	this->m_arrPadding.at(DIR_TOP) += vecNameSize.y;
}

**Comment by Exlodium** [comment]
If you make this a pull request, I'll accept it :)
